function demo_mcnBurden()

  opts.includeObjDetectors = 1 ;
  opts.includeKeypointDetectors = 1 ;
  modelDir = fullfile(vl_rootnn, 'data/models-import') ;

  models = {...
     'imagenet-matconvnet-alex.mat', ...
     'imagenet-vgg-verydeep-16.mat', ...
     'imagenet-resnet-101-dag.mat', ...
    } ;

  if opts.includeObjDetectors
    models = [ models { ...
     'faster-rcnn-vggvd-pascal', ...
     'faster-rcnn-vggvd-coco.mat', ...
     'ssd-mcn-pascal-vggvd-300.mat' ...
     } ] ;
   end

  if opts.includeKeypointDetectors
    models = [ models { ...
     'multipose-mpi.mat', ...
     'multipose-coco.mat',  ...
     } ] ;
  end

  for ii = 1:numel(models)
    modelPath = fullfile(modelDir, models{ii}) ;
    burden('modelPath', modelPath) ;
  end
