function runner()

  modelDir = fullfile(vl_rootnn, 'data/models-import') ;
  models = {...
     'imagenet-matconvnet-alex.mat', ...
     'faster-rcnn-vggvd-pascal', ...
     'faster-rcnn-vggvd-coco.mat', ...
     'ssd-mcn-pascal-vggvd-300.mat', ...
     'imagenet-vgg-verydeep-16.mat', ...
     'multipose-mpi.mat', ...
     'multipose-coco.mat',  ...
     'imagenet-resnet-101-dag.mat', ...
    } ;

  for ii = 1:numel(models)
    modelPath = fullfile(modelDir, models{ii}) ;
    demo_burden('modelPath', modelPath) ;
  end
