function runner

  modelDir = fullfile(vl_rootnn, 'data/models-import') ;
  models = {'imagenet-matconvnet-alex.mat', ...
            'imagenet-vgg-verydeep-16.mat', ...
            'ssd-mcn-pascal-vggvd-300.mat', ...
            'faster-rcnn-vggvd-coco.mat', ...
            'multipose-coco.mat', ...
            'multipose-mpi.mat', ...
            'imagenet-resnet-101-dag.mat'} ;

  modelTypes = {'dagnn', 'simplenn', 'dagnn', 'dagnn'} ;
  inputVars = {'input', 'x0', 'data', 'data', 'data', 'data', 'data'} ;
  helpers = {[], [], @ssd_autonn_custom_fn, @faster_rcnn_autonn_custom_fn} ;

  for ii = 1:numel(models)
    modelPath = fullfile(modelDir, models{ii}) ;
    demo_burden('modelPath', modelPath, 'inpuVar', inputVars{ii}, ...
                'helper', helpers{ii}, 'modelType', modelTypes{ii} ...
                  ) ;
  end

  %demo_burden('modelPath', fullfile(modelDir, 'imagenet-matconvnet-alex.mat'), 'inpuVar', 'input') ;
  %models(1).modelPath = fullfile(modelDir, 'imagenet-matconvnet-alex.mat') ;
  %models(1).
